services:
  - type: web
    name: meu-bot-whatsapp-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    rootDir: .
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1